//ESM
export {
  oddOrEven,
  swapTwoVariables,
  isLeapYear,
  isBinary,
  sumOfDigits,
  factorial,
  isPrime,
  fibonacciNumber,
  isPalindromeNumber,
  isPalindromeString,
  isArmstrongNumber,
  findGCD,
  isPerfectNumber,
  countDividingDigits,
  floorSquareRoot,
  powerOfReverse,
  findMinMax,
  findSecondMax,
  countArrayFrequency,
  twoSum,
} from "./problems.js";
